module.exports = {
  apps: [
    {
      name: "gateway",
      cwd: __dirname,
      script: "/usr/bin/bash",
      args: "-lc 'npm run start --prefix backend/api-gateway'",
      interpreter: "none",
      autorestart: true,
      watch: false,
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "user-service",
      cwd: __dirname,
      script: "/usr/bin/bash",
      args: "-lc 'npm run start --prefix backend/services/user-service'",
      interpreter: "none",
      autorestart: true,
      watch: false,
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "chat-service",
      cwd: __dirname,
      script: "/usr/bin/bash",
      args: "-lc 'npm run start --prefix backend/services/chat-service'",
      interpreter: "none",
      autorestart: true,
      watch: false,
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "chatbot-service",
      cwd: __dirname,
      script: "/usr/bin/bash",
      args: "-lc 'npm run start --prefix backend/services/chatbot-service'",
      interpreter: "none",
      autorestart: true,
      watch: false,
      env: {
        NODE_ENV: "production",
        REDIS_URL: process.env.REDIS_URL || "redis://127.0.0.1:6379",
        TRUST_PROXY: process.env.TRUST_PROXY || "1",
      },
    },
    {
      name: "ai-worker-service",
      cwd: __dirname,
      script: "/usr/bin/bash",
      args: "-lc 'npm run start --prefix backend/services/ai-worker-service'",
      interpreter: "none",
      autorestart: true,
      watch: false,
      env: {
        NODE_ENV: "production",
        REDIS_URL: process.env.REDIS_URL || "redis://127.0.0.1:6379",
      },
    },
    {
      name: "post-service",
      cwd: __dirname,
      script: "/usr/bin/bash",
      args: "-lc 'npm run start --prefix backend/services/post-service'",
      interpreter: "none",
      autorestart: true,
      watch: false,
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "frontend",
      cwd: __dirname,
      script: "/usr/bin/bash",
      args: "-lc 'npm run start --prefix frontend/web'",
      interpreter: "none",
      autorestart: true,
      watch: false,
      env: {
        NODE_ENV: "production",
      },
    },
  ],
};
